runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()

set encoding=utf-8

" Enable mouse for all modes
set mouse=a

" Line numbers
set number
set numberwidth=5

" Tab width
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab

" Display invisible characters
set list
set listchars=tab:▸\ ,trail:·,nbsp:·

" Mark the 80th column
set colorcolumn=80

" Allow to switch buffers without saving
set hidden

" Open new split panes to the right and bottom
set splitbelow
set splitright

" Quicker window movement
nnoremap <C-j>     <C-w>j
nnoremap <C-Down>  <C-w>j
nnoremap <C-k>     <C-w>k
nnoremap <C-Up>    <C-w>k
nnoremap <C-h>     <C-w>h
nnoremap <C-Left>  <C-w>h
nnoremap <C-l>     <C-w>l
nnoremap <C-Right> <C-w>l

" Tab completion
" will insert tab at beginning of line,
" will use completion if not at beginning
set wildmode=list:longest,list:full
function! InsertTabWrapper()
  let col = col('.') - 1
  if !col || getline('.')[col - 1] !~ '\k'
    return "\<tab>"
  else
    return "\<c-n>"
  endif
endfunction
inoremap <Tab> <c-r>=InsertTabWrapper()<cr>
inoremap <S-Tab> <c-p>

" Swap files
set backupdir=~/.vim/backup//
set directory=~/.vim/swap//
set undodir=~/.vim/undo//

" GVim settings
if has('gui_running')
  " Solarized color scheme
  set background=dark
  colorscheme solarized
  let g:solarized_visibility="normal"

  " Hide menubar
  set guioptions -=m

  " Hide toolbar
  set guioptions -=T

  " Hide scrollbars
  set guioptions -=l
  set guioptions -=L
  set guioptions -=r
  set guioptions -=R

  " Use console style tabs
  set guioptions -=e
endif

" Make ctrlp root itself at the first directory with a .ctrlp file it finds
" when traversing up the current path (see
" https://coderwall.com/p/5xv7sq/ctrlp-root-markers)
let g:ctrlp_root_markers = ['.ctrlp']

" Make ctrlp ignore directories with common name patterns
let g:ctrlp_custom_ignore = 'node_modules\|bower_components\|tmp'

" Toggle comments (tComment plugin)
nmap , gcc
vmap , gc
